---

run:
  tests: true

linters:
  enable:
    - errcheck
    - exportloopref
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unused
  disable:
    - wsl
    - prealloc
    - gochecknoglobals
  disable-all: false
  presets:
    - bugs
    - unused
  fast: true

linters-settings:
  unused:
    parameters-are-used: true
